"use client";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, FileVideo, RefreshCw } from "lucide-react";
import { useWorkspaceId } from "@multica/core/hooks";
import { issueListOptions } from "@multica/core/issues/queries";
import { projectListOptions } from "@multica/core/projects/queries";
import { youtubeStudioKeys, youtubeStudioVideoOptions, youtubeStudioVideosOptions, youtubeStudioVersionOptions, youtubeStudioVersionsOptions } from "@multica/core/youtube-studio";
import { useWorkspacePaths } from "@multica/core/paths";
import { api } from "@multica/core/api";
import { AppLink, useNavigation } from "../navigation";
import { RichContent } from "../rich-content";
import { Button } from "@multica/ui/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@multica/ui/components/ui/card";

function ErrorPanel({ retry }: { retry: () => void }) { return <Card><CardContent className="flex items-center justify-between gap-4 p-6"><p>Studio kunne ikke indlæses.</p><Button variant="outline" onClick={retry}><RefreshCw className="mr-2 size-4" />Prøv igen</Button></CardContent></Card>; }
export function YoutubeStudioPage({ videoId }: { videoId?: string }) { const wsId = useWorkspaceId(); const paths = useWorkspacePaths(); const nav = useNavigation(); const q = useQuery(youtubeStudioVideosOptions(wsId)); if (videoId) return <YoutubeStudioDetail videoId={videoId} />; if (q.isPending) return <main className="p-6"><div className="h-8 w-56 animate-pulse rounded bg-muted" /></main>; if (q.isError) return <main className="p-6"><ErrorPanel retry={() => void q.refetch()} /></main>; return <main className="mx-auto flex w-full max-w-5xl flex-col gap-8 p-6"><header><p className="text-sm font-medium uppercase tracking-widest text-muted-foreground">Production workspace</p><h1 className="mt-2 text-3xl font-semibold">YouTube Studio</h1><p className="mt-2 text-muted-foreground">Videomapper og automatisk indsamlede materialer.</p></header>{q.data.videos.length === 0 ? <ActivationCard /> : <div className="grid gap-4 sm:grid-cols-2">{q.data.videos.map((v) => <button key={v.video_id} className="text-left" onClick={() => nav.push(paths.youtubeStudioVideo(v.video_id))}><Card className="transition-colors hover:border-foreground/30"><CardHeader><CardTitle className="flex items-center gap-3"><FileVideo className="size-5 text-red-500" />{v.name}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">{v.material_count} materialer</CardContent></Card></button>)}</div>}</main>; }
function ActivationCard() { const wsId = useWorkspaceId(); const paths = useWorkspacePaths(); const nav = useNavigation(); const qc = useQueryClient(); const [projectId, setProjectId] = useState(""); const [issueId, setIssueId] = useState(""); const projects = useQuery(projectListOptions(wsId)); const issues = useQuery(issueListOptions(wsId)); const bind = useMutation({ mutationFn: () => api.bindYoutubeStudio(projectId, issueId), onSuccess: (d) => { void qc.invalidateQueries({ queryKey: youtubeStudioKeys.videos(wsId) }); nav.push(paths.youtubeStudioVideo(d.video_id)); } }); return <Card className="max-w-xl"><CardHeader><CardTitle>Aktivér et eksisterende projekt</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Vælg projekt og issue. Kun fremtidige agentafslutninger indsamles.</p><select aria-label="Projekt" className="w-full rounded-md border bg-background p-2" value={projectId} onChange={(e) => setProjectId(e.target.value)}><option value="">Vælg projekt</option>{(projects.data ?? []).map((p) => <option key={p.id} value={p.id}>{p.title}</option>)}</select><select aria-label="Issue" className="w-full rounded-md border bg-background p-2" value={issueId} onChange={(e) => setIssueId(e.target.value)}><option value="">Vælg issue</option>{(issues.data?.issues ?? []).filter((i) => i.project_id === projectId).map((i) => <option key={i.id} value={i.id}>{i.identifier} · {i.title}</option>)}</select><Button disabled={!projectId || !issueId || bind.isPending} onClick={() => bind.mutate()}>Aktivér Studio</Button></CardContent></Card>; }
function YoutubeStudioDetail({ videoId }: { videoId: string }) { const wsId = useWorkspaceId(); const paths = useWorkspacePaths(); const nav = useNavigation(); const q = useQuery(youtubeStudioVideoOptions(wsId, videoId)); if (q.isPending) return <main className="p-6"><div className="h-8 w-64 animate-pulse rounded bg-muted" /></main>; if (q.isError) return <main className="p-6"><ErrorPanel retry={() => void q.refetch()} /></main>; return <main className="mx-auto flex w-full max-w-6xl flex-col gap-6 p-6"><Button variant="ghost" className="w-fit" onClick={() => nav.push(paths.youtubeStudio())}><ArrowLeft className="mr-2 size-4" />Tilbage til Studio</Button><header><p className="text-sm text-muted-foreground">YouTube Studio / videomappe</p><h1 className="mt-1 text-3xl font-semibold">{q.data.name}</h1></header>{q.data.materials.length === 0 ? <Card><CardContent className="p-6 text-muted-foreground">Intet Markdown-issue er knyttet endnu.</CardContent></Card> : q.data.materials.map((m) => <Card key={m.artifact_id}><CardHeader><CardTitle className="flex justify-between"><span>Markdown-materiale</span><span className="text-sm font-normal text-muted-foreground">{m.ingestion.state}</span></CardTitle></CardHeader><CardContent className="space-y-4">{m.source_issue && <AppLink className="text-sm text-muted-foreground underline" href={paths.issueDetail(m.source_issue.id)}>Kilde: {m.source_issue.identifier} · {m.source_issue.title}</AppLink>}{m.current_version ? <VersionContent wsId={wsId} videoId={videoId} material={m} /> : <p className="text-muted-foreground">Næste agentafslutning indsamles automatisk.</p>}</CardContent></Card>)}</main>; }
function VersionContent({ wsId, videoId, material }: { wsId: string; videoId: string; material: import("@multica/core/types").StudioMaterial }) { const current = material.current_version; const [versionId, setVersionId] = useState(current?.id ?? ""); const [explicit, setExplicit] = useState(false); const list = useQuery(youtubeStudioVersionsOptions(wsId, videoId, material.artifact_id)); useEffect(() => { if (!explicit && current?.id) setVersionId(current.id); }, [current?.id, explicit]); const versions = useQuery({ ...youtubeStudioVersionOptions(wsId, videoId, material.artifact_id, versionId), enabled: !!versionId }); const selected = list.data?.versions.find((v) => v.id === versionId) ?? current; const content = versions.data?.markdown; return <div className="space-y-3"><label className="flex items-center gap-2 text-sm">Version<select aria-label="Version" className="rounded border bg-background p-1" value={versionId} onChange={(e) => { setExplicit(true); setVersionId(e.target.value); }}>{(list.data?.versions ?? [current]).filter(Boolean).map((v) => <option key={v!.id} value={v!.id}>{v!.version_number}</option>)}</select></label>{versions.isPending ? <p className="text-muted-foreground">Indlæser immutable Markdown…</p> : versions.isError ? <ErrorPanel retry={() => void versions.refetch()} /> : content === "" ? <p className="text-muted-foreground">Versionen indeholder ingen tekst.</p> : <RichContent content={content ?? ""} />}<p className="font-mono text-xs text-muted-foreground">SHA-256: {selected?.sha256}</p>{versions.data?.provenance && <p className="text-xs text-muted-foreground">Resultat {versions.data.provenance.source_result_id} · Task {versions.data.provenance.source_task_id}{versions.data.provenance.producer ? ` · ${versions.data.provenance.producer.name}` : ""}</p>}</div>; }
